<a href="https://colab.research.google.com/github/MaKo114/pylab5/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015114 ชื่อ : นายมนศักดิ์ มาโค

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที

In [1]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  if year % 400 == 0:
    return True
  elif year % 100 == 0:
    return False
  elif year % 4 == 0:
    return True
  else:
    return False

def day_of_year(day, month, year):
  if month == 1:
    return day
  else:
    total_days = day
    for i in range(1, month):
      total_days += days_in_month[i - 1]
    if month > 2 and leap_year(year):
      total_days += 1
    return total_days

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365

Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ

In [2]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  if year % 400 == 0:
    return True
  elif year % 100 == 0:
    return False
  elif year % 4 == 0:
    return True
  else:
    return False

def is_leap(year):
    if year % 400 == 0:
      return True
    elif year % 100 == 0:
      return False
    elif year % 4 == 0:
      return True
    else:
      return False

def day_of_year(day, month, year):
    if month == 1:
      return day
    else:
      total_days = day+1
    for i in range(1, month):
      total_days += days_in_month[i - 1]
    if month > 2 and leap_year(year):
      total_days += 1
    return total_days

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    day1_str, month1_str, year1_str = date1.split('-')
    day1 = int(day1_str)
    month1 = int(month1_str)
    year1 = int(year1_str)

    day2_str, month2_str, year2_str = date2.split('-')
    day2 = int(day2_str)
    month2 = int(month2_str)
    year2 = int(year2_str)

    if year1 == year2:
      if month1 == month2:
        return day2 - day1
      return day_of_year(day2, month2, year2) - day_of_year(day1, month1, year1)
    else:
      diff = 1
      for i in range(year1, year2):
        diff += day_in_year(i)
        diff += day_of_year(day2, month2, year2)
        diff -= day_of_year(day1, month1, year1)
      return diff

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

731
76
367
366
366
365

Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1

In [3]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    if year % 400 == 0:
        return True
    elif year % 100 == 0:
        return False
    elif year % 4 == 0:
        return True
    else:
        return False

def day_of_year(day, month, year):
    if day < 1 or month < 1 or month > 12:
        return -1
    if (month == 2 and leap_year(year) and day > 29) or (month == 2 and not leap_year(year) and day > 28) or day > days_in_month[month - 1]:
        return -1

    total_days = day

    for i in range(1, month):
        total_days += days_in_month[i - 1]

    if month > 2 and leap_year(year):
        total_days += 1

    return total_days

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    date1_parts = date1.split('-')
    date2_parts = date2.split('-')

    if len(date1_parts) != 3 or len(date2_parts) != 3:
        return -1

    if not (date1_parts[0].isdigit() and date1_parts[1].isdigit() and date1_parts[2].isdigit()):
        return -1
    if not (date2_parts[0].isdigit() and date2_parts[1].isdigit() and date2_parts[2].isdigit()):
        return -1

    day1 = int(date1_parts[0])
    month1 = int(date1_parts[1])
    year1 = int(date1_parts[2])

    day2 = int(date2_parts[0])
    month2 = int(date2_parts[1])
    year2 = int(date2_parts[2])

    if day1 < 1 or day2 < 1 or month1 < 1 or month1 > 12 or month2 < 1 or month2 > 12:
        return -1

    if (day1 > days_in_month[month1 - 1]) or (day2 > days_in_month[month2 - 1]):
        if not (month1 == 2 and leap_year(year1) and day1 == 29):
            return -1
        if not (month2 == 2 and leap_year(year2) and day2 == 29):
            return -1

    if year1 > year2 or (year1 == year2 and month1 > month2) or (year1 == year2 and month1 == month2 and day1 > day2):
        return -1

    day1_in_year = day_of_year(day1, month1, year1)
    day2_in_year = day_of_year(day2, month2, year2)

    if day1_in_year == -1 or day2_in_year == -1:
        return -1

    if year1 == year2:
        return day2_in_year - day1_in_year + 1  # เพิ่ม 1 วันเพื่อรวมวันสิ้นสุด
    else:
        diff = day_in_year(year1) - day1_in_year + day2_in_year + 1  # เพิ่ม 1 วันเพื่อรวมวันสิ้นสุด
        for i in range(year1 + 1, year2):
            diff += day_in_year(i)
        return diff

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1

1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()

In [9]:
import math

def simulate_fish_population(n, p, months=3):
  pass

# Run simulation
n = 2  # Initial number of fish
p = 10  # Monthly mortality rate

# simulate_fish_population(n, p)

# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว + 2 = 515 ตัว
def simulate_fish_population(n, p):
    # Initial population: half male, half female
    male_fish = n // 2
    female_fish = n // 2

    # Convert p from percentage to a proportion
    p = p / 100

    # Simulation parameters
    months = 120  # 10 years * 12 months
    reproduction_cycle = 3  # Reproduction cycle in months

    # Simulate population over time
    for month in range(1, months + 1):
        # Reproduction every 3 months
        print(male_fish , female_fish)
        if month % reproduction_cycle == 0 and month >= 2:
            new_babies = female_fish * 300  # Each female lays 300 eggs
            new_males = new_babies // 2     # Half are males
            new_females = new_babies // 2   # Half are females

            male_fish += new_males
            female_fish += new_females
            print(male_fish , female_fish)
        # Death rate applied each month
        male_fish = int(male_fish * (1 - p))
        female_fish = int(female_fish * (1 - p))
        print(male_fish , female_fish)
        # Report population every 3 months
        if month % 3 == 0:
            total_population = male_fish + female_fish
            print(f"Month {month}: Males: {male_fish}, Females: {female_fish}, Total: {total_population}")

# Example usage
n = 2  # Starting with 100 fish (50 males and 50 females)
p = 10   # 10% death rate per month
simulate_fish_population(n, p)

1 1
0 0
0 0
0 0
0 0
0 0
0 0
Month 3: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 6: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 9: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 12: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 15: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 18: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 21: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 24: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 27: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 30: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 33: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 36: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 39: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 42: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 45: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 48: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 51: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 54: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 57: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 60: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 63: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 66: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 69: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 72: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 75: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 78: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 81: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 84: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 87: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 90: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 93: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 96: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 99: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 102: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 105: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 108: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 111: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 114: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 117: Males: 0, Females: 0, Total: 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
Month 120: Males: 0, Females: 0, Total: 0

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน

In [4]:
def find_mismatch(str1, str2):
    def is_one_edit_away(s1, s2):
        len1, len2 = len(s1), len(s2)

        if abs(len1 - len2) > 1:
            return False

        i, j = 0, 0
        found_difference = False

        while i < len1 and j < len2:
            if s1[i] != s2[j]:
                if found_difference:
                    return False

                found_difference = True

                if len1 > len2:
                    i += 1
                elif len1 < len2:
                    j += 1
                else:
                    i += 1
                    j += 1
            else:
                i += 1
                j += 1

        return True

    str1, str2 = str1.lower(), str2.lower()

    if str1 == str2:
        return 0

    if is_one_edit_away(str1, str2):
        return 1

    return 2

word1 = input('Word1: ')
word2 = input('Word2: ')

print(find_mismatch(word1,word2))

Word1: onepiece
Word2: hunterxhunter
2

3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|

In [5]:
def find_mismatch(s1, s2):
    def is_one_edit_away(str1, str2):
        len1, len2 = len(str1), len(str2)

        if abs(len1 - len2) > 1:
            return False

        i, j = 0, 0
        found_difference = False

        while i < len1 and j < len2:
            if str1[i] != str2[j]:
                if found_difference:
                    return False

                found_difference = True

                if len1 > len2:
                    i += 1
                elif len1 < len2:
                    j += 1
                else:
                    i += 1
                    j += 1
            else:
                i += 1
                j += 1

        return True

    s1, s2 = s1.lower(), s2.lower()

    if s1 == s2:
        return 0

    if is_one_edit_away(s1, s2):
        return 1

    return 2

def spelling_correction(sentence, correct_spells):
    words = sentence.strip().split()
    corrected_words = []

    for word in words:
        if len(word) <= 2:
            corrected_words.append(word)
            continue

        found_correction = False

        for correct_word in correct_spells:
            if find_mismatch(word, correct_word) == 0:
                corrected_words.append(correct_word)
                found_correction = True
                break
            elif find_mismatch(word, correct_word) == 1:
                corrected_words.append(correct_word)
                found_correction = True
                break

        if not found_correction:
            corrected_words.append(word)

    return " ".join(corrected_words)

sentence = "Thes is the Firs cas"
correct_spells = 	['that','first','case','car']
print(spelling_correction(sentence, correct_spells))

Thes is the first case

4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]

In [6]:
def find_word_horizontal(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0])

    word_len = len(word)

    for row in range(num_rows):
        for col in range(num_cols - word_len + 1):
            match = True
            for i in range(word_len):
                if crosswords[row][col + i] != word[i]:
                    match = False
                    break
            if match:
                return [row, col]

    return None

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
print(find_word_horizontal(crosswords, word))

[2, 1]

5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]

In [7]:
def find_word_vertical(crosswords, word):
    num_rows = len(crosswords)
    num_cols = len(crosswords[0])

    word_len = len(word)

    for col in range(num_cols):
        for row in range(num_rows - word_len + 1):
            match = True
            for i in range(word_len):
                if crosswords[row + i][col] != word[i]:
                    match = False
                    break
            if match:
                return [row, col]

    return None

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
print(find_word_vertical(crosswords, word))

[1, 0]

6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```

In [8]:
def capitalize_word_in_crossword(crosswords, word):
    position = find_word_horizontal(crosswords, word)

    if position is not None:
        row, col = position
        for i in range(len(word)):
            crosswords[row][col + i] = crosswords[row][col + i].upper()
        return crosswords

    position = find_word_vertical(crosswords, word)

    if position is not None:
        row, col = position
        for i in range(len(word)):
            crosswords[row + i][col] = crosswords[row + i][col].upper()
        return crosswords

    return crosswords

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
result = capitalize_word_in_crossword(crosswords, word)
for row in result:
    print(row)

['s', 'd', 'o', 'g']
['c', 'u', 'c', 'm']
['a', 'C', 'A', 'T']
['t', 'e', 't', 'k']